### ISSUE TITLE
SPICE's get_kernel module downloads the kernels in another directory

### ISSUE THREAD

**Issue by abotiamnot** [heliopython/heliopy#371]
When I download SPICE kernels through the get_kernel module, it creates a different folder in a different directory rather than the current working directory. 

Now, when I furnish a kernel using the heliopy.spice, it displays an error, 'SPICE(NOSUCHFILE) --' since the furnish module looks for the file within the current working directory, and not the new directory created by get_kernel module. 

I think the get_kernel module should be fixed to download the files in the os.getcwd() path.

**Comment by dstansby** [comment]
It's meant to download to the heliopy data download folder. http://docs.heliopy.org/en/stable/data/spice.html#heliopy.data.spice.get_kernel returns the location in the local filesystem of the kernel, so that can just directly be given to furnish.

I need to tidy the `heliopy.data.spice` docs up though, so I will open a couple of other issues around that.
